@rem Gradle startup script for Windows (generated by Gradle).
@rem Requires gradle\wrapper\gradle-wrapper.jar. If missing, open the project in
@rem Android Studio (it generates the wrapper) or run `gradle wrapper`.
@if "%DEBUG%"=="" @echo off
setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_HOME=%DIRNAME%

set CLASSPATH=%APP_HOME%gradle\wrapper\gradle-wrapper.jar

if not exist "%CLASSPATH%" (
    echo ERROR: gradle\wrapper\gradle-wrapper.jar tidak ditemukan.
    echo Buka project di Android Studio atau jalankan: gradle wrapper
    exit /b 1
)

if defined JAVA_HOME (
    set JAVA_EXE=%JAVA_HOME%\bin\java.exe
) else (
    set JAVA_EXE=java.exe
)

"%JAVA_EXE%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

endlocal
