#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#
# Requires gradle/wrapper/gradle-wrapper.jar. If it is missing, open the project
# in Android Studio (it will generate the wrapper automatically) or run
# `gradle wrapper` once if you have Gradle installed.
#

set -e

APP_HOME=$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)
APP_BASE_NAME=$(basename "$0")

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    echo "ERROR: gradle/wrapper/gradle-wrapper.jar tidak ditemukan." >&2
    echo "Buka project ini di Android Studio (wrapper akan dibuat otomatis)," >&2
    echo "atau jalankan 'gradle wrapper' jika Gradle sudah terpasang." >&2
    exit 1
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
